### ISSUE TITLE
Crossover Final Review Ticket

### ISSUE THREAD

**Issue by yashakhoshini** [yashakhoshini/yasha-fastpages#26]
_**Night at the museum**_

- [x] [Event blog](https://yashakhoshini.github.io/yasha-fastpages/markdown/notm/2023/02/24/notm-dumbtrade.html)

_**Crossover Grading**_

- [x] [Table with crossover grades on project](https://github.com/yashakhoshini/yasha-fastpages/issues/27#issue-1601994947)
- [x] [Crossover grading CPT Kaiden & Nikhil](https://github.com/yashakhoshini/yasha-fastpages/issues/28#issue-1602010027)
- [x] [Crossover grading CPT self](https://github.com/yashakhoshini/yasha-fastpages/issues/30#issue-1603327902)

_**DumbTrade**_

- [x] [Final project blog]()
_Key features: interactive stock data / charting, real time stock information_
_Talk about goals (wanted to learn about how to use API's and we did this...) from the beginning, accomplishments, and improvement areas(include pictures and embedded code.)_

- Runtime (binary criteria below, 3 points + bonus)

  - Observe project quality,  runs on cross domain, performs all evaluations without crashing.
    - [website](https://dumbtrade.duckdns.org/)
  - Observe, UI contains inputs that are validated for garbage, data cleaned (ie validate DOB or Password)
    - [stock input](https://dumbtrade.duckdns.org/projects/portfoli0/)
  - Observe, UI contains actions for Create, Read,
    - [Interactive web page with API](https://dumbtrade.duckdns.org/projects/portfoli0/)
- Code Review (binary criteria below,  4 points  + bonus) 
  - Project quality, review and observe comments in every function, class, or method reviewed.
    - show code
  - BE review, observe if API handles error conditions (ie duplicate user id)
    - [API backend](https://github.com/yashakhoshini/stockbackend/blob/main/api/stock.py)
  - BE review,  observe if API contains GET and POST methods
    - [API code containing GET and POST methods](https://github.com/yashakhoshini/stockbackend/blob/main/api/stock.py)
  - BE review, observe that code contains database operations that support Create, Read
    - [Different API containing database](https://github.com/gigtieup/GroupA/blob/main/Stock.py)

**Comment by kaiden-dough** [comment]
7/7

**Comment by nikhilc3** [comment]
7/7
